# apiVersion: v1
# kind: ResourceQuota
# metadata:
#   name: compute-resources
# spec:
#   hard:
#     requests.cpu: "375m"
#     requests.memory: 384Mi
#     limits.cpu: "2"
#     limits.memory: 2Gi
