kind: Secret
apiVersion: v1
metadata:
  name: recipes
type: Opaque
data:
  # echo -n 'db-password' | base64
  postgresql-password: Y2FuWW91QmVsaWV2ZVRoaXNpc015UGFzc3dvcmQ/Cg==
  # echo -n 'postgres-user-password' | base64
  postgresql-postgres-password: d2FpdE9yaXNpdFRoaXNPbmU/P09oVGhpc2lzYURlbW8K
  # echo -n 'secret-key' | sha256sum | awk '{ printf $1 }' | base64
  secret-key: MDU4OTIyNzVkOWJhYWQ4NGJiYTJjNmJiYTc3NDgwMGM1MmMyZmU2NTI5NzgzN2ZmMThkYTcyYzRlMmFmNTZmZQ==
