name: recipes-nginx
image: nginx:latest
imagePullPolicy: IfNotPresent
ports:
  - containerPort: 80
    protocol: TCP
    name: http
  - containerPort: 8080
    protocol: TCP
    name: gunicorn
resources:
  requests:
    cpu: 125m
    memory: 64Mi
volumeMounts:
  - mountPath: /media
    name: media
    # mount as subPath due to lost+found on ext4 pvc
    subPath: files
  - mountPath: /static
    name: static
    # mount as subPath due to lost+found on ext4 pvc
    subPath: files
  - name: nginx-config
    mountPath: /etc/nginx/nginx.conf
    subPath: nginx-config
    readOnly: true
name: recipes
image: vabene1111/recipes
imagePullPolicy: IfNotPresent
command:
  - /opt/recipes/venv/bin/gunicorn
  - -b
  - :8080
  - --access-logfile
  - "-"
  - --error-logfile
  - "-"
  - --log-level
  - INFO
  - recipes.wsgi
livenessProbe:
  failureThreshold: 3
  httpGet:
    path: /
    port: 8080
    scheme: HTTP
  periodSeconds: 30
readinessProbe:
  httpGet:
    path: /
    port: 8080
    scheme: HTTP
  periodSeconds: 30
resources:
  requests:
    cpu: 125m
    memory: 64Mi
volumeMounts:
  - mountPath: /opt/recipes/mediafiles
    name: media
    # mount as subPath due to lost+found on ext4 pvc
    subPath: files
  - mountPath: /opt/recipes/staticfiles
    name: static
    # mount as subPath due to lost+found on ext4 pvc
    subPath: files
env:
  - name: DEBUG
    value: "0"
  - name: ALLOWED_HOSTS
    value: '*'
  - name: SECRET_KEY
    valueFrom:
      secretKeyRef:
        name: recipes
        key: secret-key
  - name: GUNICORN_MEDIA
    value: "0"
  - name: DB_ENGINE
    value: django.db.backends.postgresql
  - name: POSTGRES_HOST
    value: recipes-postgresql
  - name: POSTGRES_PORT
    value: "5432"
  - name: POSTGRES_USER
    value: postgres
  - name: POSTGRES_DB
    value: recipes
  - name: POSTGRES_PASSWORD
    valueFrom:
      secretKeyRef:
        name: recipes
        key: postgresql-postgres-password
securityContext:
  runAsUser: 65534
